### ISSUE TITLE
Support for msvc 16 (Visual Studio 2019)

### ISSUE THREAD

**Issue by fzwoch** [paleozogt/MSVCDocker#3]
I wonder if its "easy" to add support for msvc 16? It wasn't sure what I have to do to add this target to the tool-chain.

**Comment by paleozogt** [comment]
If you're up for submitting a patch, I can give you some pointers.  (I may not be able to get around to it as quickly as I'd like.)

Here's what you need to do:
 * Add "16" to the `msvcs` variable in `Vagrantfile`
 * Add "16" to the `MSVC_VERS` variable in `Makefile`
 * Add "16" to the `MSVC_VERS` variable in `examples/Makefile`
 * Add an `ElseIf` for "16" to `vagranttools/setup_msvc.ps1`

That last step is the hard part.  You'll have to figure out if msvc 16 is available from the chocolatey package manager (if possible, try to use "build tools" and not the full MSVC IDE installation).  Then you'll need to get the paths to the vcvars batch files.  It might have its own installation quirks to workaround (I'm looking at you, msvc 15).

The build is modularized, so you should be able to test just the vagrant part alone by running `make snapshot16`.  Or once you have the snapshot made, you can build just the docker part with `make buildimage16`.

When just getting started, I find its simpler to just spin up a fresh image (`make setupbasebox`), open up the Windows gui, and try stuff manually in a PowerShell window.  Then once I know how the installation works, I can bring the PowerShell code over to `setup_msvc.ps1`.

**Comment by paleozogt** [comment]
I've brought your changes over to master.  Thanks!
